/******************************************************************************
 Group: CMCU LPRF
 $Target Device: DEVICES $

 ******************************************************************************
 $License: BSD3 2024 $
 ******************************************************************************
 $Release Name: PACKAGE NAME $
 $Release Date: PACKAGE RELEASE DATE $
 *****************************************************************************/

/*
 *  ======== ti_zigbee_config.h.xdt ========
 */
/*
 *                           ti_zigbee_config.h
 *
 *  DO NOT EDIT - This file was generated by the SysConfig tool.
 *
 *  Macros used to define a TI Z-Stack ZigBee device.
 *
 */

#ifndef TI_ZIGBEE_CONFIG_H
#define TI_ZIGBEE_CONFIG_H

#ifdef __cplusplus
extern "C"
{
#endif


/******************************************************************************
 * INCLUDES
 */
#include "zboss_api.h"
/******************************************************************************
 * CONSTANTS
 */

/******************************************************************************
 * CONFIGURATION
 */

#ifndef DEFAULT_CHANLIST
#define DEFAULT_CHANLIST            0x00000800
#endif

/* Value used by end device when sending End Device Timeout Request */
#ifndef ED_TIMEOUT_VALUE
#define ED_TIMEOUT_VALUE        ED_AGING_TIMEOUT_256MIN
#endif

/* Default network key. */
#ifndef DEFAULT_NWK_KEY
#define DEFAULT_NWK_KEY           {0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x12,0x34}
#endif

#ifndef MAX_CHILDREN
#define MAX_CHILDREN             20
#endif

#ifndef MAX_ED_CAPACITY
#define MAX_ED_CAPACITY          10
#endif

#ifndef ED_RX_ALWAYS_ON
#define ED_RX_ALWAYS_ON         ZB_FALSE
#endif

/* The number of milliseconds to wait between data request polls to the coordinator. */
#ifndef ED_POLL_RATE
#define ED_POLL_RATE             3000
#endif

#ifdef __cplusplus
}  /* end of extern "C" */
#endif

#endif /* TI_ZIGBEE_CONFIG_H */