/******************************************************************************
 Group: CMCU LPRF
 $Target Device: DEVICES $

 ******************************************************************************
 $License: BSD3 2024 $
 ******************************************************************************
 $Release Name: PACKAGE NAME $
 $Release Date: PACKAGE RELEASE DATE $
 *****************************************************************************/

/*
 *  ======== ti_zigbee_config.c.xdt ========
 */


/*
 *                           ti_zigbee_config.h
 *
 *  DO NOT EDIT - This file was generated by the SysConfig tool.
 *
 *  Macros used to define a TI Z-Stack ZigBee device.
 *
 */
#define ZB_TRACE_FILE_ID 30006

/******************************************************************************
 * INCLUDES
 */
 #include "ti_drivers_config.h"
 #include "ti_zigbee_config.h"
 #include "zb_common.h"
 #include "zb_hal_utils.h"

/******************************************************************************
 * CONSTANTS
 */

/******************************************************************************
 * CONFIGURATION
 */


const ti_zigbee_config zigbeeConfig = {
    .aesecbIndex = CONFIG_AESECB_ZB,
    .aesccmIndex = CONFIG_AESCCM_ZB,
    .rngIndex    = CONFIG_RNG_ZB,
    .nvsIndex    = CONFIG_NVSINTERNAL_ZB,
    .sha2Index    = CONFIG_SHA2_ZB,
    .ecdhIndex    = CONFIG_ECDH_ZB,
};
